# /api/v1 공통 라우터 집합
# 팀원 가이드: 새 도메인 라우터를 만들면 이 파일에 include_router만 추가하면 된다.
#
# 추가 예시:
#   from app.domains.news.adapter.inbound.api.news_router import router as news_router
#   api_v1_router.include_router(news_router)

from fastapi import APIRouter

from app.domains.account.adapter.inbound.api.account_router import router as account_router
from app.domains.account.adapter.inbound.api.users_router import router as users_router
from app.domains.agent.adapter.inbound.api.agent_router import router as agent_router
from app.domains.auth.adapter.inbound.api.auth_router import router as auth_router
from app.domains.kakao_auth.adapter.inbound.api.kakao_auth_router import router as kakao_auth_router
from app.domains.api_schema.adapter.inbound.api.api_schema_router import router as api_schema_router
from app.domains.news.adapter.inbound.api.news_router import router as news_router
from app.domains.board.adapter.inbound.api.board_router import router as board_router
from app.domains.market_video.adapter.inbound.api.market_video_router import router as market_video_router
from app.domains.post.adapter.inbound.api.post_router import router as post_router
from app.domains.disclosure.adapter.inbound.api.disclosure_router import router as disclosure_router
from app.domains.stock.adapter.inbound.api.stock_router import router as stock_router
from app.domains.stock_theme.adapter.inbound.api.stock_theme_router import router as stock_theme_router
from app.domains.stock_theme.adapter.inbound.api.stocks_router import router as stocks_router
from app.domains.market_analysis.adapter.inbound.api.market_analysis_router import router as market_analysis_router
from app.domains.news.adapter.inbound.api.news_collect_router import router as news_collect_router
from app.adapter.inbound.api.health_router import router as health_router
from app.domains.investment.adapter.inbound.api.investment_router import router as investment_router
from app.domains.dashboard.adapter.inbound.api.dashboard_router import router as dashboard_router
from app.domains.history_agent.adapter.inbound.api.history_agent_router import router as history_agent_router
from app.domains.macro.adapter.inbound.api.macro_router import router as macro_router
from app.domains.study.adapter.inbound.api.study_router import router as study_router
from app.domains.schedule.adapter.inbound.api.schedule_router import router as schedule_router
from app.domains.company_profile.adapter.inbound.api.company_profile_router import router as company_profile_router

# 모든 API는 /api/v1 prefix를 가진다.
api_v1_router = APIRouter(prefix="/api/v1")

# --- 도메인 라우터 등록 ---
api_v1_router.include_router(board_router)      # BOARD: /api/v1/board/...
api_v1_router.include_router(market_video_router)  # MARKET VIDEO: /api/v1/youtube/...
api_v1_router.include_router(post_router)       # POST: /api/v1/post/...
api_v1_router.include_router(stock_router)      # STOCK: /api/v1/stock/...
api_v1_router.include_router(stock_theme_router)  # STOCK THEME: /api/v1/stock-theme/...
api_v1_router.include_router(stocks_router)       # STOCKS: /api/v1/stocks/themes, /api/v1/stocks?theme=
api_v1_router.include_router(agent_router)       # AGENT: /api/v1/agent/...
api_v1_router.include_router(api_schema_router)  # AGENT SCHEMA: /api/v1/agent-schema
api_v1_router.include_router(news_router)        # NEWS: /api/v1/news/...
api_v1_router.include_router(auth_router)        # AUTH: /api/v1/auth/...
api_v1_router.include_router(kakao_auth_router)  # KAKAO AUTH: /api/v1/kakao-authentication/...
api_v1_router.include_router(account_router)     # ACCOUNT: /api/v1/account/...
api_v1_router.include_router(users_router)       # USERS: /api/v1/users/me/watchlist
api_v1_router.include_router(market_analysis_router)  # MARKET ANALYSIS: /api/v1/market-analysis/...
api_v1_router.include_router(news_collect_router)    # NEWS COLLECT: /api/v1/news/collect
api_v1_router.include_router(disclosure_router)  # DISCLOSURE: /api/v1/disclosure/...
api_v1_router.include_router(health_router)      # HEALTH: /api/v1/health/...
api_v1_router.include_router(market_analysis_router)  # MARKET ANALYSIS: /api/v1/market-analysis/...
api_v1_router.include_router(investment_router)  # INVESTMENT: /api/v1/investment/...
api_v1_router.include_router(dashboard_router)       # DASHBOARD: /api/v1/dashboard/...
api_v1_router.include_router(history_agent_router)   # HISTORY AGENT: /api/v1/history-agent/...
api_v1_router.include_router(macro_router)       # MACRO: /api/v1/macro/...
api_v1_router.include_router(study_router)    # STUDY: /api/v1/study/...
api_v1_router.include_router(schedule_router)  # SCHEDULE: /api/v1/schedule/...
api_v1_router.include_router(company_profile_router)  # COMPANY PROFILE: /api/v1/company-profile/...
# api_v1_router.include_router(finance_router)  # 재무 에이전트
