"""create_sns_posts_table

Revision ID: 5491cba9a993
Revises: 0006
Create Date: 2026-04-28 02:21:45.265055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5491cba9a993'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sns_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False, comment='reddit | naver_finance | toss_community | x | facebook'),
    sa.Column('post_id', sa.String(length=100), nullable=False, comment='플랫폼 자체 게시물 ID (예: reddit submission id, 네이버 토론글 ID)'),
    sa.Column('post_hash', sa.String(length=64), nullable=False, comment='sha256(platform + post_id) - 중복 방지용 전역 unique key'),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='검색에 사용한 종목 티커 (005930, AAPL 등). 인덱스 필수.'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='게시물 제목 (Reddit submission title 등). 댓글이면 null.'),
    sa.Column('content', sa.Text(), nullable=False, comment='본문 텍스트. 감정분석의 입력. 길이 제한 X (Text).'),
    sa.Column('url', sa.Text(), nullable=True, comment='원본 게시물 URL (있는 경우만)'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='작성자 닉네임/아이디 (선택)'),
    sa.Column('score', sa.Integer(), nullable=True, comment='플랫폼 자체 점수 (Reddit upvote, 네이버 추천 수 등). 가중치 계산용.'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='댓글 수 (참여도 지표)'),
    sa.Column('extra_meta', sa.Text(), nullable=True, comment='플랫폼별 추가 메타데이터 JSON 문자열 (subreddit 이름, 추천비율 등)'),
    sa.Column('posted_at', sa.DateTime(), nullable=True, comment='게시물이 작성된 시각 (플랫폼 기준)'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='수집 시각 (우리 서버 기준)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'post_id', name='uq_sns_posts_platform_postid'),
    sa.UniqueConstraint('post_hash')
    )
    op.create_index('ix_sns_posts_collected_at', 'sns_posts', ['collected_at'], unique=False)
    op.create_index('ix_sns_posts_ticker_platform', 'sns_posts', ['ticker', 'platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_sns_posts_ticker_platform', table_name='sns_posts')
    op.drop_index('ix_sns_posts_collected_at', table_name='sns_posts')
    op.drop_table('sns_posts')
